# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.5.0
_src_path: gh:radio-aktywne/template-database-cockroach
accountname: radio-aktywne
databasename: datashows
description: Broadcast shows data 🎭
docs: true
docsurl: https://radio-aktywne.github.io/datashows
envprefix: DATASHOWS
httpport: 34001
imagename: databases/datashows
registry: true
releases: true
reponame: datashows
repourl: https://github.com/radio-aktywne/datashows
rpcport: 34002
sqlport: 34000
