# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.4.0
_src_path: gh:radio-aktywne/template-database-cockroach
accountname: radio-aktywne
databasename: datashows
description: Emission shows database 🎭💾
docs: true
docsurl: https://radio-aktywne.github.io/database-datashows
envprefix: DATASHOWS
httpport: 34001
imagename: databases/datashows
registry: true
releases: true
reponame: database-datashows
repourl: https://github.com/radio-aktywne/database-datashows
rpcport: 34002
sqlport: 34000
