# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.1
_src_path: gh:radio-aktywne/template-database-cockroach
accountname: radio-aktywne
databasename: emishows-db
description: Emission shows database 🎭💾
docs: true
docsurl: https://radio-aktywne.github.io/database-emishows-db
envprefix: EMISHOWS_DB
httpport: 34001
imagename: databases/emishows-db
registry: true
releases: true
reponame: database-emishows-db
repourl: https://github.com/radio-aktywne/database-emishows-db
rpcport: 34002
sqlport: 34000
