services:
  emishows-db:
    build:
      context: ./
      network: host
    environment:
      - "EMISHOWS_DB__SERVER__HOST=${EMISHOWS_DB__SERVER__HOST:-0.0.0.0}"
      - "EMISHOWS_DB__SERVER__PORTS__SQL=${EMISHOWS_DB__SERVER__PORTS__SQL:-34000}"
      - "EMISHOWS_DB__SERVER__PORTS__HTTP=${EMISHOWS_DB__SERVER__PORTS__HTTP:-34001}"
      - "EMISHOWS_DB__SERVER__PORTS__RPC=${EMISHOWS_DB__SERVER__PORTS__RPC:-34002}"
      - "EMISHOWS_DB__CREDENTIALS__ROOT__PASSWORD=${EMISHOWS_DB__CREDENTIALS__ROOT__PASSWORD:-password}"
      - "EMISHOWS_DB__CREDENTIALS__USER__PASSWORD=${EMISHOWS_DB__CREDENTIALS__USER__PASSWORD:-password}"
    network_mode: host
    privileged: true
    volumes:
      - data:/database/data/

volumes:
  data: {}
